### ISSUE TITLE
Postmaster item count inaccurate

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#260]
Postmaster can save up to 40 items--20 public event, cryptarch, faction packages + 20 weapons, shaders, emblems, engrams. Current displayed total is incorrect:
![2015-06-20_143013](https://cloud.githubusercontent.com/assets/3769123/8269352/6558aa04-1759-11e5-821c-985996b32b2d.png)

**Comment by dasilva333** [comment]
Expect this fixed in the next version thanks

**Comment by M3Rocket** [comment]
Found another bug whereby not ALL packages are being shown nor counted at the postmaster.

This is what is showing on Bungie.net:
![image](https://cloud.githubusercontent.com/assets/3769123/8369188/d44ddad2-1b6a-11e5-91f1-d1bda883af4c.png)

This is what is showing on TGD 2.8.0:
![image](https://cloud.githubusercontent.com/assets/3769123/8369214/11fe5a3c-1b6b-11e5-8f60-58a232cfc3d6.png)

This is what is showing in DIM 3.0.12:
![image](https://cloud.githubusercontent.com/assets/3769123/8369232/4526327c-1b6b-11e5-9b47-2648432c7502.png)

**Comment by dasilva333** [comment]
This is an easy fix expect it resolved in the next version

**Comment by dasilva333** [comment]
This has been fixed as of version 2.8.4+ not all channels have this version available yet will be working on making sure all platforms are up to date. thanks guys

**Comment by M3Rocket** [comment]
Just FYI, I'm running Chrome 2.8.5 and it still shows ??/20.
