### ISSUE TITLE
Since iOS 9 the resolution is very small (iPhone 6)

### ISSUE THREAD

**Issue by aap007** [dasilva333/TowerGhostForDestiny#417]
Hello,

I noticed the resolution is very small, almost like I am opening it on a iPhone 4. This started since I upgraded to iOS 9.

Here a screenshot:
![image2](https://cloud.githubusercontent.com/assets/10104857/10196722/95ed222c-6794-11e5-8a04-c004c55a6d0f.PNG)

And a screenshot of the normal resolution:
![image1](https://cloud.githubusercontent.com/assets/10104857/10196742/ae824bd2-6794-11e5-8080-9e065d0f2ea5.PNG)

Thank you in advance!

Love the app!!

**Comment by lightmaster** [comment]
Looks under View -> View Options and set "XS" to 1. If that doesn't work, go down the list of those options setting them to 1

**Comment by aap007** [comment]
Thank you for the response Lightmaster.

I am afraid I wasn't clear enough. I didn't mean the view settings of the columns, but the number of pixels TGD uses for the width and height. TGD doesn't uses the native resolution anymore..

As an example I found old screenshot of the app.
![img_3592](https://cloud.githubusercontent.com/assets/10104857/10573341/357b891e-764f-11e5-9aef-560e2e3e6ac1.PNG)

As you can see very clearly with the bottom popup dialog, the old version uses the native resolution as the new version doesn't anymore. This started since updating to iOS 9 and using the iOS 9 version.

**Comment by lightmaster** [comment]
Oh, I see what you meant now, how everything seems bigger and blurrier.

**Comment by aap007** [comment]
Yes indeed.

**Comment by dasilva333** [comment]
Hey guys the latest version was submitted with Phonegap 3.7.0 which might have messed up your resolution (still unsure as to the cause), the next version coming to the Apple Store 3.4.3 should have the problem addressed. Try it out when it's out and let me know if it's still an issue. Thanks

**Comment by aap007** [comment]
Thank you for the fix Richard Pinedo. I will supply an update when version 3.4.3 is available.

**Comment by dasilva333** [comment]
3.4.3 has been available and the problem should be resolved. Thanks

**Comment by aap007** [comment]
Due to holidays I didn't had time to respond quicker. Unfortunately the problem still exists in 3.4.3.

I don't know if it has anything to do with it, but one of the items of the release notes for iOS 9.1 from apple:
- Resolves an issue that zoomed the content of some apps.

I have updated to iOS 9.1 as well but this also doesn't solve the problem.

**Comment by dasilva333** [comment]
Let's wait until 3.4.7 is released and let me know what the outcome of that it is. Thanks

**Comment by aap007** [comment]
It is fixed! Thank you very much!
