### ISSUE TITLE
Still not loading on iPad

### ISSUE THREAD

**Issue by DogBeatr** [dasilva333/TowerGhostForDestiny#471]
Just downloaded the new update today (Nov 24 2015) and now there is a large white box that covers the screen (see attached photo). The update box describing what's new very briefly shows then this box. As you can see in the top left corner, a small portion of the screen shows. Tried reinstalling numerous times. Hoping to be able to use this app again soon. 

![image](https://cloud.githubusercontent.com/assets/15177960/11389007/cab31b1a-9309-11e5-928e-ef3dad874923.png)

**Comment by DogBeatr** [comment]
Ok, I changed the orientation of my iPad and it works now. It seems to happen only when you open the app in landscape view. Btw thanks for adding the save as option.

**Comment by DogBeatr** [comment]
Nope, still major issues in landscape and portrait view sometimes loads properly

**Comment by griffinmills** [comment]
Having the same issue here on ipad, ios 8.3.

Same steps of downloading repeatedly.  Didn't even think to try portrait mode!  Although that is mostly the same for me, big white box.  Was working okayish prior to udpate but was having a very hard time showing armor, hence why I updated.

**Comment by dasilva333** [comment]
Sorry guys I tested this on my 5s (ios 8/9) and 6s (ios 9) and it seems to work fine, lets try a few things to figure this problem out.

1. When the app does work load in portrait what is the version number reported on the top left?
2. Try disabling and enabling Auto Updates from the settings to see if 3.6.1.7 fixes your problem
3. Make sure that if you do reinstall you uninstall first and then install 

Thanks guys

**Comment by abqwizard** [comment]
No that does not fix it on the iPad. it updated to 3.6.1.7 and there are still major problems with landscape mode. I even deleted it and reinstalled, updated again to 3.6.1.7 and no dice. Just a little slice at the bottom in portrait mode and landscape is still a slice of black at the left and the rest is just white screen.

**Comment by abqwizard** [comment]
Okay so starting in portrait mode works, but starting in landscape mode still has the same problem.

**Comment by dasilva333** [comment]
This is really strange, no one seems to be reporting this for Android so it might be iPad only issue, I'll produce a debug build so we can figure out this problem. Maybe @ssoriche could also try it on his iPad and confirm the issue. Thanks guys

**Comment by gxb2089** [comment]
Hi. Having same issue with white box showing up at first load time. Change in orientation trick worked for me.

**Comment by BustaMuns** [comment]
I have the both iPad and android version of app. I get the white screen on my iPad and my android will not allow me to transfer any items. I press an item and no profiles come up on the bottom to transfer or equip. Android has version 3.6.1.6 iPad has 3.6.1

**Comment by tmalfor** [comment]
I have the same problem. After I disabled and reenabled the auto update I ended up with version 3.6.3. The problem still continued. I then selected the view settings and chose the option to customize and then chose the option default. I then closed the app.  The next time I opened it the app filled the entire window in both portrait and landscape but the data didn't load. Refresh didn't help.  I then unchecked auto-update again and recheked it.  After about half a minute the data loaded. Everything seems to be working correctly now but obviously that's a lot to go through for an average person

**Comment by rkingsla** [comment]
I can confirm that I did see this issue on my iPad mini. I was able to get it to display properly by playing around with landscape and portrait orientation, and mentioned by others. But, did have the exact same issue as @abqwizard and @DogBeatr

**Comment by piyo** [comment]
Hello I also had the same problem on my iPad mini 2 and iPad 3 (2012). "Start in portrait orientation" workaround works for me.

**Comment by TheWalt2** [comment]
Closing the app (shutting down with double home button click) and reopening in portrait mode is what got it working again for me.

**Comment by BustaMuns** [comment]
I was able to view and use the app using that strategy and now I just leave it open. When I want to go back to it I double click the home button and open it that way. Cause sometimes it still takes a couple times for the app open correctly when using portrait to open it.

**Comment by Kwanx** [comment]
Same issue as DogBeatr on iPad2, iOS 9.1, tried rebooting/reinstalling = same issue. Portrait works though. Lmk if you need more info, happy to help. Thx for a great app!

**Comment by dasilva333** [comment]
Hey guys I still haven't figured out a solution, I can't think of why this is happening or what I can do to debug the issue remotely. I think the only way I can resolve this at this point is with me having the actual device to figure this out manually. I'm looking into either buying an iPad or going to a library to try to use that for debugging. Anyhow don't expect it fixed any time soon. Thanks everyone

**Comment by weborican** [comment]
I have a few damaged iPads (cracked screen) that otherwise work just fine, but are not getting repaired and could use a good home. Contact me offline if you need a test device.

**Comment by dasilva333** [comment]
Sure @weborican email me at support@towerghostfordestiny.com and we can work something out that would be great thanks a lot :)

**Comment by MasterBry** [comment]
When I shut it right down and open it in portrate it works fine, i then just tip it back to landscape and its all been working perfectly... Well up until the Destiny update this week, now its not :-(

**Comment by dasilva333** [comment]
Hey guys thanks to @weborican's generosity I was able to debug the issue and get it fixed as of version 3.7.0.2, try it out via Auto Updates or when it's out in the store and let me know if anyone still has a problem.

**Comment by MasterBry** [comment]
Thanks for all the fixes, still won't load in landscape but that's no big deal, I just load in  portrait and turn it on it's side :-)

Awesome app use it all the time, and lost when it's not working,  keep up the GREAT work

**Comment by dasilva333** [comment]
@MasterBry 3.7.0.2 should fix that.  I'll do further testing to confirm the fix. You can check your version under Settings > About

**Comment by MasterBry** [comment]
I am in 3.7.0.2 :-) 
I have auto update and auto refresh selected for last two weeks. .. it's all good

**Comment by dasilva333** [comment]
I'm able to confirm the store updated version does not fix it. Now I just have to figure out why the fix doesn't work for the store version. Stay tuned

**Comment by dasilva333** [comment]
@MasterBry Problem fixed as of 3.7.0.3 try it again

**Comment by MasterBry** [comment]
Sorry was soloing Crota for the hell of it.

Dude it Auto Updated to version 3.6.7.3 !!

**Comment by MasterBry** [comment]
so I unticked the auto update it updated again and now it is 3.7.0.3 and it loaded in landscape. .. so you have fixed it :-) 
You are awesome

**Comment by DogBeatr** [comment]
Set the auto update and landscape is now working for me too. Thanks!!

**Comment by weborican** [comment]
Confirmed working as of version 3.7.0.3!
