### ISSUE TITLE
Emblem image is missing.

### ISSUE THREAD

**Issue by karlwilbur** [dasilva333/TowerGhostForDestiny#652]
![screenshot from 2016-08-25 19 37 59](https://cloud.githubusercontent.com/assets/55618/17989486/a3794c5c-6afb-11e6-8861-0b46ba6ea08d.png)
When I load Tower Ghost in Google Chrome, all characters using the "Hear the Call" emblem (Year 2 Moments of Triumph reward) are missing their emblem image. Switching to a different, older emblem and updating Tower Ghost will then display the correct emblem for that character. Switching back to Hear the Call will just leave the older emblem displayed after refresh.

Not really a functional issue but it *does* make it slightly more difficult to transfer items to characters because their mouse target is small (only the letter "H", "W", or "T").

**Comment by karlwilbur** [comment]
This may be related to #632.

**Comment by dasilva333** [comment]
Consider the problem fixed as of 3.9.2, let me know if it's still an issue thanks

**Comment by karlwilbur** [comment]
This seems to be partly fixed in 3.9.1.3.

![screenshot from 2016-08-26 16 32 10](https://cloud.githubusercontent.com/assets/55618/18019535/8f402738-6baa-11e6-9d3f-5c3934dc10c4.png)

**Comment by dasilva333** [comment]
It should be fully fixed now, let me know if there's still any issues. Thanks!

**Comment by rkingsla** [comment]
FWIW, I still see the images for the Moments of Triumph missing in the loadout or multi-item transfer screen.  Merely a nit, I know.

**Comment by karlwilbur** [comment]
Yes, there are are still some places missing the "Hear the Call" emblem (see attached screenshots). Again, this is *not* an issue with functionality. It still works for transferring items but the mouse target is smaller that what was intended because the image is missing.

Using Hear the Call:
![screenshot from 2016-08-31 14 24 53](https://cloud.githubusercontent.com/assets/55618/18141343/2a57fc2a-6f87-11e6-840a-b37bbe0e7f3e.png)

Not using Hear the Call:
![screenshot from 2016-08-31 14 29 00](https://cloud.githubusercontent.com/assets/55618/18141368/3dbf52e0-6f87-11e6-9ff9-372ae262b3a1.png)

**Comment by karlwilbur** [comment]
Should I make a new issue for this or would you rather re-open this one?

**Comment by rkingsla** [comment]
I'll save everyone the trouble. The reply to Richard's email that I sent and the one from @karlwilbur are both fixed in a coming update. From the latest commits:

![2016-08-31_15-10-45](https://cloud.githubusercontent.com/assets/2037051/18144667/530b7ac4-6f8d-11e6-926d-649be89974e9.png)
![2016-08-31_15-10-09](https://cloud.githubusercontent.com/assets/2037051/18144671/59d7b106-6f8d-11e6-8b69-a499de3a114b.png)

**Comment by karlwilbur** [comment]
Excellent!! Thanks!
